# main에 대한 pull_request가 closed될 때 workflow를 실행
on:
  pull_request:
    branches:
      - main
    types:
      - closed
  workflow_dispatch: #수동 실행도 가능하도록
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


# ssh로 접속하여 새로운 버전 배포
jobs:
  release:
    runs-on: ubuntu-latest
    # pr의 결과가 merged인 경우만 jobs를 실행
    if: github.event.pull_request.merged == true

    steps:
    # ssh로 EC2 접속
    - name: Connect EC2 by SSH
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        first_ssh: |
          ${{ secrets.AUTHORIZATION }}
          fuser -k {{ secrets.APPLIATION_PORT}}/tcp && cd ${{ secrets.PROJECT_PATH }}
          git fetch && git pull
          git clone --bare {{ secrets.SECRET_REPOSITORY }}
          ./gradlew clean build -x test
          rm nohup.out
          nohup java -jar {{ secrets.APPLICATION_PATH }} &
